Generating sequence of the dates

In [1]:
import pandas as pd
import numpy as np
df= pd.date_range('28-05-2026',periods=6)
print(df)

DatetimeIndex(['2026-05-28', '2026-05-29', '2026-05-30', '2026-05-31',
               '2026-06-01', '2026-06-02'],
              dtype='datetime64[us]', freq='D')

In [17]:
df= pd.read_csv('tips.csv')
# print(df.to_string())

print(pd.options.display.max_rows)

#it diplays all the rows of the csv file
# print(df.to_string())

#custom rows
pd.options.display.max_rows=200
print(df)

200
     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
res = df[df['total_bill']>20]
res

     total_bill    tip     sex smoker   day    time  size
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
7         26.88   3.12    Male     No   Sun  Dinner     4
11        35.26   5.00  Female     No   Sun  Dinner     4
15        21.58   3.92    Male     No   Sun  Dinner     2
19        20.65   3.35    Male     No   Sat  Dinner     3
21        20.29   2.75  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
28        21.70   4.30    Male     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
35        24.06   3.60    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
52        34.81   5.20  Female     No   Sun  Dinner     4
54        25.56   4.34    Male     No   Sun  Dinner     4
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
65        20.08   3.15    Male     No   Sat  Dinner     3
68        20.23   2.01    Male     No   Sat  Dinner     2
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
78        22.76   3.00    Male     No  Thur   Lunch     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
89        21.16   3.00    Male     No  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
91        22.49   3.50    Male     No   Fri  Dinner     2
94        22.75   3.25  Female     No   Fri  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
96        27.28   4.00    Male    Yes   Fri  Dinner     2
98        21.01   3.00    Male    Yes   Fri  Dinner     2
102       44.30   2.50  Female    Yes   Sat  Dinner     3
103       22.42   3.48  Female    Yes   Sat  Dinner     2
104       20.92   4.08  Female     No   Sat  Dinner     2
106       20.49   4.06    Male    Yes   Sat  Dinner     2
107       25.21   4.29    Male    Yes   Sat  Dinner     2
112       38.07   4.00    Male     No   Sun  Dinner     3
113       23.95   2.55    Male     No   Sun  Dinner     2
114       25.71   4.00  Female     No   Sun  Dinner     3
116       29.93   5.07    Male     No   Sun  Dinner     4
119       24.08   2.92  Female     No  Thur   Lunch     4
125       29.80   4.20  Female     No  Thur   Lunch     6
129       22.82   2.18    Male     No  Thur   Lunch     3
131       20.27   2.83  Female     No  Thur   Lunch     2
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
153       24.55   2.00    Male     No   Sun  Dinner     4
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
157       25.00   3.75  Female     No   Sun  Dinner     4
160       21.50   3.50    Male     No   Sun  Dinner     4
165       24.52   3.48    Male     No   Sun  Dinner     3
166       20.76   2.24    Male     No   Sun  Dinner     2
167       31.71   4.50    Male     No   Sun  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3
173       31.85   3.18    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
184       40.55   3.00    Male    Yes   Sun  Dinner     2
185       20.69   5.00    Male     No   Sun  Dinner     5
186       20.90   3.50  Female    Yes   Sun  Dinner     3
187       30.46   2.00    Male    Yes   Sun  Dinner     5
189       23.10   4.00    Male    Yes   Sun  Dinner     3
192       28.44   2.56    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
204       20.53   4.00    Male    Yes  Thur   Lunch     4
206       26.59   3.41    Male    Yes   Sat  Dinner     3
207       38.73   3.00    Male    Yes   Sat  Dinner     4
208       24.27   2.03    Male    Yes   Sat  Dinner     2
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
216       28.15   3.00    Male    Yes   Sat  Dinner     5
219       30.14   3.09  Female    Yes   Sat  Dinner     4
227       20.45   3.00    Male     No   Sat  Dinner     4
229       22.12   2.88  Female    Yes   Sat  Dinner     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3
240       27.18   2.00  Female    Yes   Sat  Dinner     2
241       22.67   2.00    Male    Yes   Sat  Dinner     2

In [20]:
#Value_count

res1 = df['day'].value_counts()
print(res1)

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [21]:
df= pd.read_json('tips.json')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [29]:
#Removing the empty rows
df= pd.read_csv('tips.csv')
# print(df)


#Deleting the empty rows
# df.dropna(inplace=True)
# print(df)

#Filling empty cells

#replace by the value
# df.fillna({ 'total_bill': 0 ,'time':'-'}, inplace=True)


#Repalce by the mean, mode , median
x = df['total_bill'].mean()
df.fillna({'total_bill':x},inplace = True)
print(df)

     total_bill   tip     sex smoker   day    time  size
0      19.83166  1.01  Female     No   Sun  Dinner     2
1      19.83166  1.66    Male     No   Sun  Dinner     3
2      19.83166  3.50    Male     No   Sun  Dinner     3
3      23.68000  3.31    Male     No   Sun  Dinner     2
4      24.59000  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239    29.03000  5.92    Male     No   Sat  Dinner     3
240    27.18000  2.00  Female    Yes   Sat  Dinner     2
241    22.67000  2.00    Male    Yes   Sat  Dinner     2
242    17.82000  1.75    Male     No   Sat  Dinner     2
243    18.78000  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Numpy..........

In [36]:
import numpy as np 
print(np.__version__)

a= np.array([1,2,3,4,5])
print(a,type(a))
print(a.dtype)

2.4.6
[1 2 3 4 5] <class 'numpy.ndarray'>
int64

In [37]:
#2 [] brackets then 2- Dimensional array , if 7 [] then 7- dimensional aray

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]

In [41]:
c = np.zeros(6)
print(c)

[0. 0. 0. 0. 0. 0.]

In [42]:
#@-D array.....
d= np.ones((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
#3-d
d= np.ones((4,2,3))
d

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])