In [3]:
#1) Convert a series of date-strings to a timeseries?

import pandas as pd
dates = pd.Series([
    '2026-05-01',
    '2026-05-02',
    '2026-05-03'
])
print("Original Series:")
print(dates)

timeseries = pd.to_datetime(dates)
print("\n Converted Series:")
print(timeseries)

Original Series:
0    2026-05-01
1    2026-05-02
2    2026-05-03
dtype: str

 Converted Series:
0   2026-05-01
1   2026-05-02
2   2026-05-03
dtype: datetime64[us]

In [6]:
#2)Create two DataFrames, df1 and df2, with a common column (e.g., 'ID').
df1 = pd.DataFrame({
    'id' :[1,2,3,4],
    'Name':["Kani","Dishu","Ram","Shyam"],
    'section':["A","B","C","D"]
})

df2 =pd.DataFrame({
    'id' :[1,2,3,4],
    'Name':["Kajal","Dis","Dishu","Sam"],
    'section':["A","F","E","D"]
})
print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

DataFrame 1:
   id   Name section
0   1   Kani       A
1   2  Dishu       B
2   3    Ram       C
3   4  Shyam       D

DataFrame 2:
   id   Name section
0   1  Kajal       A
1   2    Dis       F
2   3  Dishu       E
3   4    Sam       D

In [7]:
#>Perform an inner merge on this common column and display the resulting DataFrame.
res = df1.merge(df2,on = 'id',how='inner')
print(res)

   id Name_x section_x Name_y section_y
0   1   Kani         A  Kajal         A
1   2  Dishu         B    Dis         F
2   3    Ram         C  Dishu         E
3   4  Shyam         D    Sam         D

In [9]:
#>Perform a left join of df1 and df2 on the 'ID' column. Explain how missing values are handled in the resulting DataFrame. Right Join and Index-Based Join.

print("\n Left Join:")

left=df1.merge(df2,on='id',how="left")
left

 Left Join:

   id Name_x section_x Name_y section_y
0   1   Kani         A  Kajal         A
1   2  Dishu         B    Dis         F
2   3    Ram         C  Dishu         E
3   4  Shyam         D    Sam         D

In [11]:
#Right Join
print("\nRight Join:")
Right=df1.merge(df2,on='id',how="right")
Right

Right Join:

   id Name_x section_x Name_y section_y
0   1   Kani         A  Kajal         A
1   2  Dishu         B    Dis         F
2   3    Ram         C  Dishu         E
3   4  Shyam         D    Sam         D

In [16]:
#Index-Based Join.
df1_index=df1.set_index('id')
df2_index=df2.set_index('id')
print(df1_index)
print(df2_index)

res1=df1_index.join(
    df2_index,
    how='right',
    lsuffix='_df1',
    rsuffix='_df2'
)
print(res1)

     Name section
id
1    Kani       A
2   Dishu       B
3     Ram       C
4   Shyam       D
     Name section
id
1   Kajal       A
2     Dis       F
3   Dishu       E
4     Sam       D
   Name_df1 section_df1 Name_df2 section_df2
id
1      Kani           A    Kajal           A
2     Dishu           B      Dis           F
3       Ram           C    Dishu           E
4     Shyam           D      Sam           D

In [ ]:
#>Perform a right join using pd.merge() on a common column, then perform a join using df.join() based on the index. Compare the results. Merging with Multiple Keys.

print("Merging Right.....")
r_join = df1.merge(df2,on="id",how='right')
print(r_join)
#using index based.....
print("\nIndex based join.....")
df1_index=df1.set_index('id')
df2_index=df2.set_index('id')
index_rjoin=df1_index.join(
    df2_index,
    how='right',
    lsuffix='_df1',
    rsuffix='_df2'
)
print(index_rjoin)

# MERGING WITH MULTIPLE KEYS

print("\n MERGING WITH MULTIPLE KEYS ")

multi_key_merge = pd.merge(
    df1,
    df2,
    on=['id', 'section'],
    how='inner',
    # suffixes=('_df1', '_df2')
)

print(multi_key_merge)

Merging Right.....
   id Name_x section_x Name_y section_y
0   1   Kani         A  Kajal         A
1   2  Dishu         B    Dis         F
2   3    Ram         C  Dishu         E
3   4  Shyam         D    Sam         D

Index based join.....
   Name_df1 section_df1 Name_df2 section_df2
id
1      Kani           A    Kajal           A
2     Dishu           B      Dis           F
3       Ram           C    Dishu           E
4     Shyam           D      Sam           D

 MERGING WITH MULTIPLE KEYS
   id Name_df1 section Name_df2
0   1     Kani       A    Kajal
1   4    Shyam       D      Sam

In [33]:
df1 = pd.DataFrame({
    'id' :[1,2,3,4],
    'Name':["Kani","Dishu","Ram","Shyam"],
    'section':["A","B","C","D"]
})

df2 =pd.DataFrame({
    'id' :[1,2,3,4],
    'Name':["Kajal","Dis","Dishu","Sam"],
    'section':["A","F","E","D"]
})

df3 =pd.DataFrame({
    'id' :[1,2,3,4],
    'Name':["Kaju","Sis","Jij","Fish"],
    'section':["A","G","S","T"]
})


print("Dataframe 1:\n",df1)
print("\nDataframe 2:\n",df2)
print("\nDataframe 3:\n",df3)

#Concatination.....................
print("\nConcatinationg the df1 and df2:")
concat_res= pd.concat([df1,df2],axis=0)
print(concat_res)

#Merging with 3rd df
print("\nMerging the concat res and df3:")
ans = concat_res.merge(df3,on= 'id',how='inner')
print(ans)

Dataframe 1:
    id   Name section
0   1   Kani       A
1   2  Dishu       B
2   3    Ram       C
3   4  Shyam       D

Dataframe 2:
    id   Name section
0   1  Kajal       A
1   2    Dis       F
2   3  Dishu       E
3   4    Sam       D

Dataframe 3:
    id  Name section
0   1  Kaju       A
1   2   Sis       G
2   3   Jij       S
3   4  Fish       T

Concatinationg the df1 and df2:
   id   Name section
0   1   Kani       A
1   2  Dishu       B
2   3    Ram       C
3   4  Shyam       D
0   1  Kajal       A
1   2    Dis       F
2   3  Dishu       E
3   4    Sam       D

Merging the concat res and df3:
   id Name_x section_x Name_y section_y
0   1   Kani         A   Kaju         A
1   2  Dishu         B    Sis         G
2   3    Ram         C    Jij         S
3   4  Shyam         D   Fish         T
4   1  Kajal         A   Kaju         A
5   2    Dis         F    Sis         G
6   3  Dishu         E    Jij         S
7   4    Sam         D   Fish         T